server:
  port: 9091
  address: 127.0.0.1
  tomcat:
    accesslog:
      enabled: true
      pattern: "%{X-Forwarded-For}i %l %u %t \"%r\" %s %b %D"
      directory: logs/access
      prefix: access_log
      suffix: .log
      file-date-format: .yyyy-MM-dd

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.web.filter.RequestLoggingFilter: DEBUG
    org.springframework.boot.web.servlet.context: DEBUG
    org.rogmann.mcp2sdk.chat: DEBUG

# Web-UI Konfiguration
webui:
  public:
    #path: ...
  model:
    #name: Qwen3.6-27B
    #url: http://...
  hasVision: false
  hasAudio: false
  max:
    #tokens: 240000

# Tool Configuration
tools:
  # Comma-separated list of tool names to activate on startup
  active: "glossary-tool,find_files_by_glob,get_file_text_by_path,edit_file"
